### ISSUE TITLE
Electrode (+) (-) mixup - problem for neurokit?

### ISSUE THREAD

**Issue by Raphael-Rissler** [neuropsychology/NeuroKit.py#27]
Hello, 

I've a little question about neuroKit. If someone mixed up the (+) and (-) placement of the electrodes in ECG measurement, which means, you have a negative peaked heart beats (see picture below) instead of a positive peaked.

Now the question is: Does this affect the data analysis and is the output of your gr8 tool still valid in such a case?

![negative_peak_heart_beat](https://user-images.githubusercontent.com/15125455/28766217-e1e1fdac-75ce-11e7-996b-350664931048.PNG)

Best Regards and Thanks

**Comment by DominiqueMakowski** [comment]
See #11
