### ISSUE TITLE
reading data from .acq

### ISSUE THREAD

**Issue by bobchicken** [neuropsychology/NeuroKit.py#32]
Hi 

I'm trying to read my data from Acqknowledge file but it doesn't look right at all. It seems like it displays values for only one channel, where there are in fact three. Is there something I can do to get it load properly? I just find nothing works on the Acqknowledge data - even the plots look wrong, displaying the signal for a few of the recorded minutes. I'm completely new to this so apologies if this is an obvious question - just completely lost on what to do with it. 

Thanks a lot

**Comment by DominiqueMakowski** [comment]
@bobchicken Could you send me one acq file by mail at dom.mak19@gmail.com? I'll try to fix your problem

**Comment by bobchicken** [comment]
Thanks a lot Dominique, files sent.

**Comment by DominiqueMakowski** [comment]
@bobchicken did it work?

**Comment by bobchicken** [comment]
Hi Dominique - sorry for the late reply I have been away from work for a
while! Thank you so much  for sending that over. It did work, however still
displaying only one channel. I'm going to work with a new Port next week so
will see how that goes.

Thanks a lot!

K
