### ISSUE TITLE
suggestion for pandas version

### ISSUE THREAD

**Issue by vcuculo** [neuropsychology/NeuroKit.py#48]
It seems that in the code you refer to the method `DataFrame.rolling()` inserted since pandas version `>=0.18.0`. To avoid errors as :

> AttributeError: 'DataFrame' object has no attribute 'rolling'

it would be good to insert the minimum pandas version in setup.py or requirements.txt

**Comment by DominiqueMakowski** [comment]
Thanks for the suggestion @vcuculo, the fix has been added in the [next version](https://github.com/neuropsychology/NeuroKit.py/pull/49). Let us know if you find any more bugs 😄
