### ISSUE TITLE
[Bug] R_Peaks changed by ecg_hrv

### ISSUE THREAD

**Issue by lilinned** [neuropsychology/NeuroKit.py#52]
Following lines in function `ecg_hrv`:
`beats_times = rpeaks[1:]`
`beats_times -= beats_times[0]`
change values in rpeaks, which is a direct reference to the result returned by `ecg_process`. 

In short, the bug causes the `ecg_process` to return incorrect r_peak indices.
One quick fix is to copy the sliced array:
`beats_times = rpeaks[1:].copy()`

**Comment by DominiqueMakowski** [comment]
Wow, thanks for noticing that out 😃 
This has been fixed in current version #53 

Nice work, let me know if you find anything else!
