### ISSUE TITLE
python 2 compatibility: make bio_eda compatible

### ISSUE THREAD

**Issue by ucohen** [neuropsychology/NeuroKit.py#82]
in order to have bio_eda compatible, in **cvxEDA** need to change:
    frequency = 1/sampling_rate
to 
    frequency = 1./sampling_rate

**Comment by DominiqueMakowski** [comment]
@ucohen thanks for pointing this out. Would you like to make a small PR with this change yourself :) ?

**Comment by DominiqueMakowski** [comment]
Fixed by #83
